package com.example.agriecommerce.config;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

@Data
@Configuration
@ConfigurationProperties(prefix = "app")
public class JwtConfig {
    private String jwtSecret;
    private long jwtExpirationMs;
    private long jwtRefreshExpirationMs;
    private String frontendUrls;

    // Getters are automatically generated by @Data
}